return {
	-- These misions are listed differently in packets, only current mission id is mentioned.
	copmissions = {
		[1] = {id=101, name="Ancient Flames Beckon"},
		[2] = {id=110, name="__The Rites of Life"},
		[3] = {id=118, name="__Below the Arks"},
		[4] = {id=128, name="__The Mothercrystals"},
		[5] = {id=137, name="The Isle of Forgotten Saints"},
		[6] = {id=138, name="__An Invitation West"},
		[7] = {id=218, name="__The Lost City"},
		[8] = {id=228, name="__Distant Beliefs"},
		[9] = {id=238, name="__An Eternal Melody"},
		[10] = {id=248, name="__Ancient Vows"},
		[11] = {id=257, name="A Transient Dream"},
		[12] = {id=258, name="__The Call of the Wyrmking"},
		[13] = {id=318, name="__A Vessel Without a Captain"},
		[14] = {id=325, name="__The Road Forks"},
		[15] = {id=330, name="____Emerald Waters"},
		[16] = {id=331, name="______Vicissitudes"},
		[17] = {id=335, name="______Descendants of a Line Lost"},
		[18] = {id=339, name="______Louverance"},
		[19] = {id=340, name="____Memories of a Maiden"},
		[20] = {id=341, name="______Comedy of Errors, Act I"},
		[21] = {id=345, name="______Comedy of Errors, Act II"},
		[22] = {id=349, name="______Exit Stage Left"},
		[23] = {id=350, name="__Tending Aged Wounds"},
		[24] = {id=358, name="__Darkness Named"},
		[25] = {id=367, name="The Cradles of Children Lost"},
		[26] = {id=368, name="__Sheltering Doubt"},
		[27] = {id=418, name="__The Savage"},
		[28] = {id=428, name="__The Secrets of Worship"},
		[29] = {id=438, name="__Slanderous Utterings"},
		[30] = {id=447, name="The Return Home"},
		[31] = {id=448, name="__The Enduring Tumult of War"},
		[32] = {id=518, name="__Desires of Emptiness"},
		[33] = {id=530, name="__Three Paths"},
		[34] = {id=540, name="____Past Sins"},
		[35] = {id=542, name="______Southern Legend"},
		[36] = {id=543, name="______Partners Without Fame"},
		[37] = {id=546, name="______A Century of Hardship"},
		[38] = {id=549, name="______Departures"},
		[39] = {id=550, name="____The Pursuit of Paradise"},
		[40] = {id=552, name="______Spiral"},
		[41] = {id=553, name="______Branded"},
		[42] = {id=556, name="______Pride and Honor"},
		[43] = {id=559, name="______And the Compass Guides"},
		[44] = {id=560, name="____Where Messengers Gather"},
		[45] = {id=562, name="______Entanglement"},
		[46] = {id=564, name="______Head Wind"},
		[47] = {id=568, name="______Flames for the Dead"},
		[48] = {id=577, name="Echoes of Time"},
		[49] = {id=578, name="__For Whom the Verse Is Sung"},
		[50] = {id=618, name="__A Place to Return"},
		[51] = {id=628, name="__More Questions Than Answers"},
		[52] = {id=638, name="__One to Be Feared"},
		[53] = {id=647, name="In the Light of the Crystal"},
		[54] = {id=648, name="__Chains and Bonds"},
		[55] = {id=718, name="__Flames in the Darkness"},
		[56] = {id=728, name="__Fire in the Eyes of Men"},
		[57] = {id=738, name="__Calm Before the Storm"},
		[58] = {id=748, name="__The Warrior's Path"},
		[59] = {id=758, name="Emptiness Bleeds"},
		[60] = {id=800, name="__Garden of Antiquity"},
		[61] = {id=818, name="__A Fate Decided"},
		[62] = {id=828, name="__When Angels Fall"},
		[63] = {id=840, name="__Dawn"},
		--[64] = {id=850, name="__The Last Verse"},
		--[65] = {id=1000, name="To Begin CoP..."},
	},
	acpmissions = {
		[1] = {id=0, name="A Crystalline Prophecy"},
		[2] = {id=1, name="The Echo Awakens"},
		[3] = {id=2, name="Gatherer of Light (I)"},
		[4] = {id=3, name="Gatherer of Light (II)"},
		[5] = {id=4, name="Those Who Lurk in Shadows (I)"},
		[6] = {id=5, name="Those Who Lurk in Shadows (II)"},
		[7] = {id=6, name="Those Who Lurk in Shadows (III)"},
		[8] = {id=7, name="Remember Me in Your Dreams"},
		[9] = {id=8, name="Born of Her Nightmares"},
		[10] = {id=9, name="Banishing the Echo"},
		[11] = {id=10, name="Ode of Life Bestowing"},
		--[12] = {id=11, name="A Crystalline Prophecy (Fin.)"},
		--[13] = {id=1000, name="To commence ACP"},
	},
	mkdmissions = {
		[1] = {id=0, name="A Moogle Kupo d'Etat"},
		[2] = {id=1, name="Drenched! It Began with a Raindrop"},
		[3] = {id=2, name="Hasten! In a Jam in Jeuno?"},
		[4] = {id=3, name="Welcome! To My Decrepit Domicile"},
		[5] = {id=4, name="Curses! A Horrifically Harrowing Hex"},
		[6] = {id=5, name="An Errand! The Professor's Price"},
		[7] = {id=6, name="Shock! Arrant Abuse of Authority"},
		[8] = {id=7, name="Lender Beware! Read the Fine Print"},
		[9] = {id=8, name="Rescue! A Moogle's Labor of Love"},
		[10] = {id=9, name="Roar! A Cat Burglar Bares Her Fangs"},
		[11] = {id=10, name="Relief! A Triumphant Return"},
		[12] = {id=11, name="Joy! Summoned to a Fabulous Fete"},
		[13] = {id=12, name="A Challenge! You Could Be a Winner"},
		[14] = {id=13, name="Smash! A Malevolent Menace"},
		--[15] = {id=14, name="A Moogle Kupo d'Etat (Fin.)"},
	},
	asamissions = {
		[1] = {id=0, name="A Shantotto Ascension"},
		[2] = {id=1, name="Burgeoning Dread"},
		[3] = {id=2, name="That Which Curdles Blood"},
		[4] = {id=3, name="Sugar-coated Directive"},
		[5] = {id=4, name="Enemy of the Empire (I)"},
		[6] = {id=5, name="Enemy of the Empire (II)"},
		[7] = {id=6, name="Sugar-coated Subterfuge"},
		[8] = {id=7, name="Shantotto in Chains"},
		[9] = {id=8, name="Fountain of Trouble"},
		[10] = {id=9, name="Battaru Royale"},
		[11] = {id=10, name="Romancing the Clone"},
		[12] = {id=11, name="Sisters in Arms"},
		[13] = {id=12, name="Project: Shantottofication"},
		[14] = {id=13, name="An Uneasy Peace"},
		--[15] = {id=14, name="A Shantotto Ascension (Fin)"},
		--[16] = {id=1000, name="To Begin ASA..."},
	},
	soamissions = {
		[1] = {id=110, name="The Sacred City of Adoulin"},
		[2] = {id=110, name="__Rumors from the West"},
		[3] = {id=112, name="__The Geomagnetron"},
		[4] = {id=116, name="__Onward to Adoulin"},
		[5] = {id=120, name="__Heartwings and the Kindhearted"},
		[6] = {id=122, name="__Pioneer Registration"},
		[7] = {id=124, name="__Life on the Frontier"},
		[8] = {id=126, name="__Meeting of the Minds"},
		[9] = {id=128, name="__Arciela Appears Again"},
		[10] = {id=132, name="The Ancient Pact"},
		[11] = {id=132, name="__Budding Prospects"},
		[12] = {id=134, name="____The Light Shining in Your Eyes"},
		[13] = {id=136, name="____The Heirloom"},
		[14] = {id=138, name="__An Aimless Journey"},
		[15] = {id=140, name="____Ortharsyne"},
		[16] = {id=142, name="____In the Presence of Royalty"},
		[17] = {id=144, name="__The Twin World Trees"},
		[18] = {id=146, name="__Honor and Audacity"},
		[19] = {id=148, name="____The Watergarden Coliseum"},
		[20] = {id=150, name="__Friction and Fissures"},
		[21] = {id=152, name="____The Celennia Memorial Library"},
		[22] = {id=156, name="____For Whom Do We Toil?"},
		[23] = {id=162, name="__Aiming for Ygnas"},
		[24] = {id=164, name="____Calamity in the Kitchen"},
		[25] = {id=168, name="____Arciela's Promise"},
		[26] = {id=170, name="__Predators and Prey"},
		[27] = {id=172, name="____Behind the Sluices"},
		[28] = {id=178, name="____The Leafkin Monarch"},
		[29] = {id=180, name="____Yggdrasil"},
		[30] = {id=184, name="Shadows Upon Adoulin"},
		[31] = {id=184, name="__Return of the Exorcist"},
		[32] = {id=186, name="____The Merciless One"},
		[33] = {id=188, name="____A Curse from the Past"},
		[34] = {id=190, name="____The Purgation"},
		[35] = {id=192, name="____The Key"},
		[36] = {id=194, name="__The Princess's Dilemma"},
		[37] = {id=196, name="____Dark Clouds Ahead"},
		[38] = {id=198, name="____The Smallest of Favors"},
		[39] = {id=200, name="__Summoned by Spirits"},
		[40] = {id=202, name="____Evil Entities"},
		[41] = {id=204, name="____Adoulin Calling"},
		[42] = {id=206, name="____The Disappearance of Nyline"},
		[43] = {id=208, name="____Shared Consciousness"},
		[44] = {id=210, name="____Clear Skies"},
		[45] = {id=212, name="__The Man in Black"},
		[46] = {id=214, name="____To the Victor..."},
		[47] = {id=216, name="____An Extraordinary Gentleman"},
		[48] = {id=220, name="____The Order's Treasures"},
		[49] = {id=222, name="____August's Heirloom"},
		[50] = {id=224, name="__Beauty and the Beast"},
		[51] = {id=226, name="____Wildcat with a Gold Pelt"},
		[52] = {id=228, name="____In Search of Arciela"},
		[53] = {id=232, name="____Looking For Leads"},
		[54] = {id=234, name="__Drifting Northwest"},
		[55] = {id=236, name="____Kumhau, the Flashfrost Naakual"},
		[56] = {id=242, name="____Soul Siphon"},
		[57] = {id=244, name="____Stonewalled"},
		[58] = {id=248, name="____Salvation"},
		[59] = {id=250, name="____Glimmer of Portent"},
		[60] = {id=252, name="The Serpentine Labyrinth"},
		[61] = {id=252, name="__...Into the Fire"},
		[62] = {id=254, name="____Melvien de Malecroix"},
		[63] = {id=256, name="____Courier Catastrophe"},
		[64] = {id=258, name="____Done and Delivered"},
		[65] = {id=260, name="____Ministerial Whispers"},
		[66] = {id=262, name="____A Day in the Life of a Pioneer"},
		[67] = {id=264, name="__Lighting the Way"},
		[68] = {id=266, name="____Sajj'aka"},
		[69] = {id=268, name="____Studying Up"},
		[70] = {id=270, name="____A Vow of Truth"},
		[71] = {id=272, name="____Darrcuiln"},
		[72] = {id=274, name="__The Gates"},
		[73] = {id=278, name="____Morimar"},
		[74] = {id=280, name="____A New Force Arises"},
		[75] = {id=282, name="____The Sacred Sapling"},
		[76] = {id=284, name="____Tree Grafting"},
		[77] = {id=286, name="____A Shrouded Canopy"},
		[78] = {id=288, name="____Leafallia"},
		[79] = {id=290, name="____Rosulatia's Promise"},
		[80] = {id=292, name="____The Lightsland"},
		[81] = {id=294, name="____The Light of Dawn Comes..."},
		[82] = {id=296, name="__Cries from the Deep"},
		[83] = {id=298, name="____Seeds of Doubt"},
		[84] = {id=300, name="____The Tomatoes of Wrath"},
		[85] = {id=302, name="____A Grave Mistake"},
		[86] = {id=306, name="____An Emergency Convocation"},
		[87] = {id=308, name="__Balamor, the Deathborne Xol"},
		[88] = {id=310, name="____Anagnorisis"},
		[89] = {id=312, name="____Just the Thing"},
		[90] = {id=314, name="____Sugarcoated Salvation"},
		[91] = {id=316, name="____Arciela's Resolve"},
		[92] = {id=318, name="__Balamor's Ruse"},
		[93] = {id=320, name="____The Charlatan"},
		[94] = {id=324, name="____Royal Blessings"},
		[95] = {id=326, name="Hades"},
		[96] = {id=326, name="__Arboreal Rumors"},
		[97] = {id=328, name="____Arciela's Missive"},
		[98] = {id=330, name="____Heroes, Unite!"},
		[99] = {id=332, name="____A Portent Most Ominous"},
		[100] = {id=334, name="__Yggdrasil Beckons"},
		[101] = {id=336, name="____Returning to the Trees"},
		[102] = {id=338, name="____The Key to the Turris"},
		[103] = {id=342, name="__Teodor's Summons"},
		[104] = {id=344, name="____The Seventh Guardian"},
		[105] = {id=346, name="____Watery Grave"},
		[106] = {id=350, name="____Blood for Blood"},
		[107] = {id=352, name="__Reckoning"},
		[108] = {id=356, name="____Abomination"},
		[109] = {id=360, name="__Undying Light"},
		[110] = {id=368, name="____The Light Within"},
		--[111] = {id=999, name="__fin"},
		--[112] = {id=1000, name="To begin SoA..."},
	},
	rovmissions = {
		[1] = {id=0, name="Rhapsodies of Vana'diel"},
		[2] = {id=110, name="'Chapter One: Creation and Rebirth'"},
		[3] = {id=110, name="__Resonance"},
		[4] = {id=111, name="__Emissary from the Seas"},
		[5] = {id=112, name="__Set Free"},
		[6] = {id=114, name="__The Beginning"},
		[7] = {id=118, name="__Flames of Prayer"},
		[8] = {id=120, name="__The Path Untraveled"},
		[9] = {id=126, name="__At the Heavens' Door"},
		[10] = {id=128, name="__The Lion's Roar"},
		[11] = {id=130, name="__Eddies of Despair"},
		[12] = {id=134, name="__A Land After Time"},
		[13] = {id=136, name="__Fate's Call"},
		[14] = {id=138, name="__What Lies Beyond"},
		[15] = {id=140, name="__The Ties That Bind"},
		[16] = {id=142, name="__Impurity"},
		[17] = {id=144, name="__The Lost Avatar"},
		[18] = {id=148, name="__Volto Oscuro"},
		[19] = {id=150, name="__Ring My Bell"},
		[20] = {id=152, name="Chapter Two: Revitalization"},
		[21] = {id=152, name="__Spirits Awoken"},
		[22] = {id=154, name="__Crashing Waves"},
		[23] = {id=156, name="__Call to Serve"},
		[24] = {id=158, name="__Numbering Days"},
		[25] = {id=160, name="__Inescapable Binds"},
		[26] = {id=162, name="__Desert Winds"},
		[27] = {id=164, name="__Ever Forward"},
		[28] = {id=168, name="__The Endless Sky"},
		[29] = {id=170, name="__Aphmau's Light"},
		[30] = {id=172, name="__Reunited"},
		[31] = {id=174, name="__Take Wing"},
		[32] = {id=176, name="__Prime Number"},
		[33] = {id=178, name="__From the Ruins"},
		[34] = {id=180, name="__Cauterize"},
		[35] = {id=186, name="__Uncertain Destinations"},
		[36] = {id=188, name="__Ganged Up On"},
		[37] = {id=191, name="__Sacrifice"},
		[38] = {id=194, name="__Somber Dreams"},
		[39] = {id=200, name="__Of Light and Darkness"},
		[40] = {id=202, name="__Temporary Farewells"},
		[41] = {id=204, name="__Brushing Up"},
		[42] = {id=206, name="__Keep On Giving"},
		[43] = {id=208, name="__Past Imperfect"},
		[44] = {id=209, name="__The Cursed Temple"},
		[45] = {id=211, name="__Wisdom of Our Forefathers"},
		[46] = {id=212, name="__Where Divinities Collide"},
		[47] = {id=214, name="__Visions of Dread"},
		[48] = {id=216, name="__To the Skies"},
		[49] = {id=218, name="__Escha - Ru'Aun"},
		[50] = {id=222, name="__The Decisive Heroine"},
		[51] = {id=224, name="__Fall from Grace"},
		[52] = {id=226, name="__Banishing the Darkness"},
		[53] = {id=228, name="__Over the Rainbow"},
		[54] = {id=230, name="__Cacophonous Discord"},
		[55] = {id=232, name="__Eddies of Despair"},
		[56] = {id=234, name="__Pretender to the Throne"},
		[57] = {id=238, name="__Banished"},
		[58] = {id=240, name="__Call of the Void"},
		[59] = {id=244, name="__Both Paths Taken"},
		[60] = {id=250, name="__The Man Behind the Mask"},
		[61] = {id=252, name="__Uncertain Futures"},
		[62] = {id=254, name="Chapter 3: Reckoning"},
		[63] = {id=254, name="__Darkness Beckons"},
		[64] = {id=258, name="__The Brewing Storm"},
		[65] = {id=260, name="__The River Runs Red"},
		[66] = {id=262, name="__The Crucible"},
		[67] = {id=263, name="__Forward Thinking"},
		[68] = {id=264, name="__Tears of the Generals"},
		[69] = {id=266, name="__What He Left Behind"},
		[70] = {id=268, name="__Gone but Not Forgotten"},
		[71] = {id=269, name="__August Artifacts"},
		[72] = {id=270, name="__Solemnity"},
		[73] = {id=272, name="__Eyes on You"},
		[74] = {id=274, name="__Exploring the Ruins"},
		[75] = {id=278, name="__Become Something More"},
		[76] = {id=280, name="__Unshakable Nightmares"},
		[77] = {id=282, name="__What Remains of Hope"},
		[78] = {id=286, name="__Death Cares Not"},
		[79] = {id=288, name="__No Time like the Future"},
		[80] = {id=292, name="__Sin"},
		[81] = {id=296, name="__Penance"},
		[82] = {id=298, name="__Vessel of Light"},
		[83] = {id=300, name="__The Lifestream of Reisenjima"},
		[84] = {id=302, name="__From West to East"},
		[85] = {id=304, name="__Good Things Come in Threes"},
		[86] = {id=306, name="__Tackling the Problem"},
		[87] = {id=308, name="__Way to Divinity"},
		[88] = {id=310, name="__The Winds of Time"},
		[89] = {id=314, name="__Calm After the Storm"},
		[90] = {id=318, name="__Nary a Cloud in Sight"},
		[91] = {id=320, name="__An Unending Song"},
		[92] = {id=324, name="__A Deep Sleep"},
		[93] = {id=326, name="__Guardians"},
		[94] = {id=328, name="__Iroha in Distress"},
		[95] = {id=330, name="__Absolute Trust"},
		[96] = {id=332, name="__The Orb's Radiance"},
		[97] = {id=334, name="__A Rhapsody for the Ages"},
		--[98] = {id=1000, name="To Start RoV..."},
	},
	tvrmissions = {
		[1] = {id=0, name="The Voracious Resurgence"},
		[2] = {id=110, name="__The Gloom Phantom's Approach"},
		[3] = {id=118, name="__The Brygid Cup"},
		[4] = {id=128, name="__The Destiny Destroyers"},
		[5] = {id=138, name="__Kupipi's Dilemma"},
		[6] = {id=146, name="__The Cardians' Duty"},
		[7] = {id=158, name="__Zhuu Buxu's Gambit"},
		[8] = {id=168, name="__Star Onion Fortune"},
		[9] = {id=178, name="__The Doll Whisperer"},
		[10] = {id=192, name="__Dancing Prince"},
		[11] = {id=202, name="__Claidie's Concern"},
		[12] = {id=210, name="__Curilla Unleashed"},
		[13] = {id=228, name="__Run, Excenmille, Run!"},
		[14] = {id=240, name="__Of Knights and Orcs"},
		[15] = {id=256, name="__Best Served Cold"},
		[16] = {id=270, name="__Cornelia's Call to Action"},
		[17] = {id=286, name="__Naja the Ambitious"},
		[18] = {id=298, name="__Raubahn the Blue"},
		[19] = {id=310, name="__Ghatsad's Quandary"},
		[20] = {id=326, name="__The Revelation"},
		[21] = {id=338, name="__Tateeya's Worries"},
		[22] = {id=352, name="__The Seagull Phratrie"},
		[23] = {id=362, name="__The Sea Sage"},
		[24] = {id=380, name="__Sky, Moon, Incantrix"},
		[25] = {id=392, name="__Nii's Last Stand"},
		[26] = {id=414, name="__Dance of the Tengu"},
		[27] = {id=430, name="__Raebrimm's Rebirth"},
		[28] = {id=440, name="__Uran-Mafran of the Maelstrom"},
		[29] = {id=452, name="__Koru-Moru's Hypothesis"},
		[30] = {id=460, name="__Altennia Burns Bright"},
		[31] = {id=468, name="__Maat on the Rampage"},
		[32] = {id=484, name="__Not Just a Pretty Face"},
		[33] = {id=494, name="__Delkfutt the Great"},
		[34] = {id=508, name="__Oshasha Violation"},
		[35] = {id=516, name="__Phantasmic Heroes"},
		[36] = {id=530, name="__Skokkr Undrborn's Temptation"},
		[37] = {id=542, name="__The Prime Weapons"},
		[38] = {id=552, name="__To Movalpolos!"},
		[39] = {id=562, name="__Magh Bihu on the Prowl"},
		[40] = {id=574, name="__101 Dazbogs"},
		[41] = {id=580, name="__Kipdrix the Faithful"},
		[42] = {id=592, name="__Duke Alloces's Decision"},
		[43] = {id=602, name="__Odin's Eye"},
		[44] = {id=612, name="__Moglesse Oblige"},
		[45] = {id=624, name="__The Voracious Beast"},
		--[46] = {id=642, name="__Your Decision"},
		--[47] = {id=999, name="__"},
	},
}