return {
	-- by bitfield
	-- adress 0x063 Order 3
	-- parseddata['Monster Level Char field']
	--[0]='',
	[1]='Rabbit',
	[2]='Behemoth',
	[3]='Tiger',
	[4]='Sheep',
	[5]='Ram (Sheep)',
	[6]='Dhalmel',
	[7]='Coeurl',
	[8]='Opo-opo',
	[9]='Manticore',
	[10]='Buffalo',
	[11]='Marid',
	[12]='Cerberus',
	[13]='Gnole',
	--[14]='Yztarg', --not implemented
	[15]='Funguar',
	[16]='Treant Sapling',
	[17]='Morbol',
	[18]='Mandragora',
	[19]='Sabotender',
	[20]='Flytrap',
	[21]='Goobbue',
	[22]='Rafflesia',
	[23]='Panopt',
	--[24]='Belladonna', --not implemented
	--[25]='Leafkin', --not implemented
	--[26]='Snapweed', --not implemented
	[27]='Bee',
	[28]='Beetle',
	[29]='Crawler',
	[30]='Fly',
	[31]='Scorpion',
	[32]='Spider',
	[33]='Antlion',
	[34]='Diremite',
	[35]='Chigoe',
	[36]='Wamouracampa (Wamoura larva)',
	[37]='Ladybug',
	[38]='Gnat',
	--[39]='Mantis', --not implemented
	--[40]='Kulox (Gnat)', --not implemented
	--[41]='Twitherym', --not implemented
	--[42]='Chapuli', --not implemented
	[43]='Lizard',
	[44]='Raptor',
	[45]='Adamantoise',
	[46]='Bugard',
	[47]='Eft',
	[48]='Wivre',
	[49]='Peiste',
	--[50]='Matamata', --not implemented
	--[51]='Worm', --not implemented
	[52]='Slime',
	[53]='Hecteyes',
	[54]='Flan',
	--[55]='Botulus (Flan)', --not implemented
	[56]='Slug',
	[57]='Sandworm',
	[58]='Leech',
	--[59]='Acuex', --not implemented
	[60]='Crab',
	[61]='Pugil',
	[62]='Sea Monk',
	[63]='Uragnite',
	[64]='Orobon',
	[65]='Ruszor',
	[66]='Toad',
	--[67]='Pteraketos', --not implemented
	--[68]='Craklaw', --not implemented
	[69]='Bird',
	[70]='Cockatrice',
	[71]='Roc',
	[72]='Bat',
	[73]='Hippogryph',
	[74]='Apkallu',
	[75]='Colibri',
	[76]='Amphiptere',
	--[77]='Harpeia', --not implemented
	--[78]='Tulfaire', --not implemented
	
	[254]='Astoltian Slime',
	[255]='Spriggan',
}