return {
	[0] = 'Keeping Notes',
	[1] = 'Arts And Crafts',
	[2] = 'Olduum',
	[3] = 'Got It All',
	[4] = 'Get The Picture',
	[5] = 'An Empty Vessel',
	[6] = 'Luck Of The Draw',
	[7] = 'No Strings Attached',
	[8] = 'Finding Faults',
	[9] = 'Give Peace A Chance',
	[10] = 'The Art Of War',
	--JPENTRIESORINVALID
	[12] = 'A Taste Of Honey',
	[13] = 'Such Sweet Sorrow',
	[14] = 'Fear Of The Dark Ii',
	[15] = 'Cook A Roon',
	[16] = 'The Die Is Cast',
	[17] = 'Two Horn The Savage',
	[18] = 'Totoroons Treasure Hunt',
	[19] = 'What Friends Are For',
	[20] = 'Rock Bottom',
	[21] = 'Beginnings',
	[22] = 'Omens',
	[23] = 'Transformations',
	[24] = 'Equipped For All Occasions',
	[25] = 'Navigating The Unfriendly Seas',
	[26] = 'Against All Odds',
	[27] = 'The Wayward Automaton',
	[28] = 'Operation Teatime',
	[29] = 'Puppetmaster Blues',
	[30] = 'Moment Of Truth',
	[31] = 'Three Men And A Closet',
	[32] = 'Five Seconds Of Fame',
	--JPENTRIESORINVALID
	[40] = 'The Beast Within',
	[41] = 'Breaking The Bonds Of Fate',
	--JPENTRIESORINVALID
	[43] = 'Saga Of The Skyserpent',
	[44] = 'Ode To The Serpents',
	[45] = 'When The Bow Breaks',
	[46] = 'Fist Of The People',
	[47] = 'Soothing Waters',
	[48] = 'Embers Of His Past',
	--JPENTRIESORINVALID
	[60] = 'The Prankster',
	[61] = 'Delivering The Goods',
	[62] = 'Vanishing Act',
	[63] = 'Striking A Balance',
	[64] = 'Not Meant To Be',
	[65] = 'Led Astray',
	[66] = 'Rat Race',
	[67] = 'The Prince And The Hopper',
	[68] = 'Vw Op 050 Aht Urgan Assault',
	[69] = 'Vw Op 068 Subterrainean Skirmish',
	[70] = 'An Imperial Heist',
	[71] = 'Duties Tasks And Deeds',
	[72] = 'Forging A New Myth',
	[73] = 'Coming Full Circle',
	[74] = 'Waking The Colossus',
	[75] = 'Divine Interference',
	[76] = 'The Rider Cometh',
	[77] = 'Unwavering Resolve',
	[78] = 'A Stygian Pact',
	--JPENTRIESORINVALID
	[90] = 'Promotion Private First Class',
	[91] = 'Promotion Superior Private',
	[92] = 'Promotion Lance Corporal',
	[93] = 'Promotion Corporal',
	[94] = 'Promotion Sergeant',
	[95] = 'Promotion Sergeant Major',
	[96] = 'Promotion Chief Sergeant',
	[97] = 'Promotion Second Lieutenant',
	[98] = 'Promotion First Lieutenant',
	[99] = 'Promotion Captain',
	--JPENTRIESORINVALID
	[101] = 'Scouting The Ashu Talif',
	[102] = 'Royal Painter Escort',
	[103] = 'Targeting The Captain'
}
