return {
	 --Kazham(1-15)
	[1] = 'The Firebloom Tree',
	[2] = 'Greetings To The Guardian',
	[3] = 'A Question Of Taste',
	[4] = 'Everyones Grudging',
	[6] = 'You Call That A Knife',
	[7] = 'Missionary Man',
	[8] = 'Gullibles Travels',
	[9] = 'Even More Gullibles Travels',
	[10] = 'Personal Hygiene',
	[11] = 'The Opo Opo And I',
	[12] = 'Trial By Fire',
	[13] = 'Cloak And Dagger',
	[14] = 'A Discerning Eye',
	[15] = 'Trial Size Trial By Fire',

	--Voidwatch(100-105)
	[100] = 'Voidwatch Ops Border Crossing',
	[101] = 'Vw Op 054 Elshimo List',
	[102] = 'Vw Op 101 Detour To Zepwell',
	[103] = 'Vw Op 115 Li Telor Variant',
	[104] = 'Skyward Ho Voidwatcher',

	--Norg(128-149)
	[128] = 'The Sahagins Key',
	[129] = 'Forge Your Destiny',
	[130] = 'Black Market',
	[131] = 'Mama Mia',
	[132] = 'Stop Your Whining',
	[133] = 'Trial By Water',
	[134] = 'Everyones Grudge',
	[135] = 'Secret Of The Damp Scroll',
	[136] = 'The Sahagins Stash',
	[137] = 'Its Not Your Vault',
	[138] = 'Like A Shining Subligar',
	[139] = 'Like Shining Leggings',
	[140] = 'The Sacred Katana',
	[141] = 'Yomi Okuri',
	[142] = 'A Thief In Norg',
	[143] = 'Twenty In Pirate Years',
	[144] = 'I Ll Take The Big Box',
	[145] = 'True Will',
	[146] = 'The Potential Within',
	[147] = 'Bugi Soden',
	[148] = 'Trial Size Trial By Water',
	[149] = 'An Undying Pledge',

	--Misc(160-165)
	[160] = 'Wrath Of The Opo Opos',
	[161] = 'Wandering Souls',
	[162] = 'Soul Searching',
	[163] = 'Divine Might',
	[164] = 'Divine Might Repeat',
	[165] = 'Open Sesame',

	--Rabao(192-201)
	[192] = 'Dont Forget The Antidote',
	[193] = 'The Missing Piece',
	[194] = 'Trial By Wind',
	[195] = 'The Kuftal Tour',
	[196] = 'The Immortal Lu Shang',
	[197] = 'Trial Size Trial By Wind',
	[199] = 'Chasing Dreams',
	[200] = 'The Search For Goldmane',
	[201] = 'Indomitable Spirit',
}
