return {
    [0]   = 'Beaucedine Glacier',
    [1]   = 'Buburimu Peninsula',
    [2]   = 'West Sarutabaruta',
    [3]   = 'Pashhow Marshlands',
    [4]   = 'North Gustaberg',
    [5]   = 'Jugner Forest',
    [6]   = 'Valkurm Dunes',
    [7]   = 'West Ronfaure',
	
    [8]   = 'Yhoator Jungle',
    [9]   = 'Yuhtunga Jungle',
    [10]  = 'Cape Teriggan',
    [11]  = 'Eastern Altepa Desert',
    [12]  = 'The Sanctuary of Zi\'Tah',
    [13]  = 'Meriphataud Mountains',
    [14]  = 'Qufim Island',
    [15]  = 'Xarcabard',

    [16]  = 'Garlaige Citadel',
    [17]  = 'Crawlers\' Nest',
    [18]  = 'The Eldieme Necropolis',
    [19]  = 'Toraimarai Canal',
    [20]  = 'Bostaunieux Oubliette',
    [21]  = 'Oldton Movalpolos',
    [22]  = 'Ru\'Aun Gardens',
    [23]  = 'Lufaise Meadows',

    [24]  = 'Rolanberry Fields',
    [25]  = 'Konschtat Highlands',
    [26]  = 'Batallia Downs',
    [27]  = 'La Theine Plateau',
    [28]  = 'Ru\'Lude Gardens',
    [29]  = 'Port Windurst',
    [30]  = 'Bastok Mines',
    [31]  = 'Northern San d\'Oria',

    [32]  = 'Ranguemont Pass',
    [33]  = 'Castle Zvahl Baileys',
    [34]  = 'Castle Oztroja',
    [35]  = 'Davoi',
    [36]  = 'Beadeaux',
    [37]  = 'Fort Ghelsba',
    [38]  = 'Sauromugue Champaign',
    [39]  = 'Tahrongi Canyon',

    [40]  = 'Ro\'Maeve',
    [41]  = 'Maze of Shakhrami',
    [42]  = 'Gusgen Mines',
    [43]  = 'Ordelle\'s Caves',
    [44]  = 'Inner Horutoto Ruins',
    [45]  = 'Dangruf Wadi',
    [46]  = 'King Ranperre\'s Tomb',
    [47]  = 'Lower Delkfutt\'s Tower',

    [48]  = 'Carpenters\' Landing',
    [49]  = 'Labyrinth of Onzozo',
    [50]  = 'Gustav Tunnel',
    [51]  = 'Sea Serpent Grotto',
    [52]  = 'Kuftal Tunnel',
    [53]  = 'Korroloka Tunnel',
    [54]  = 'Temple of Uggalepih',
    [55]  = 'Western Altepa Desert',

    [56]  = 'East Ronfaure [S]',
    [57]  = 'Aydeewa Subterrane',
    [58]  = 'Mamook',
    [59]  = 'Wajaom Woodlands',
    [60]  = 'Sacrarium',
    [61]  = 'Phomiuna Aqueducts',
    [62]  = 'Misareaux Coast',
    [63]  = 'Bibiki Bay',

    [64]  = 'West Sarutabaruta [S]',
    [65]  = 'Rolanberry Fields [S]',
    [66]  = 'Pashhow Marshlands [S]',
    [67]  = 'Grauberg [S]',
    [68]  = 'North Gustaberg [S]',
    [69]  = 'Batallia Downs [S]',
    [70]  = 'Vunkerl Inlet [S]',
    [71]  = 'Jugner Forest [S]',

    [72]  = 'The Eldieme Necropolis [S]',
    [73]  = 'Crawlers\' Nest [S]',
    [74]  = 'Garlaige Citadel [S]',
    [75]  = 'Castle Zvahl Baileys [S]',
    [76]  = 'Beaucedine Glacier [S]',
    [77]  = 'Sauromugue Champaign [S]',
    [78]  = 'Meriphataud Mountains [S]',
    [79]  = 'Fort Karugo-Narugo [S]',

    --[80]  = 'Unknown Survival Guide',
    [81]  = 'Southern San d\'Oria [S]',
    [82]  = 'Nashmau',
    [83]  = 'Aht Urhgan Whitegate',
    [84]  = 'Tavnazian Safehold',
    [85]  = 'Rabao',
    [86]  = 'Norg',
    [87]  = 'Kazham',

    [88]  = 'Ifrit\'s Cauldron',
    [89]  = 'Valley of Sorrows',
    [90]  = 'Dragon\'s Aery',
    [91]  = 'Behemoth\'s Dominion',
    [92]  = 'Halvung',
    [93]  = 'Arrapago Reef',
    [94]  = 'Caedarva Mire',
    [95]  = 'Windurst Waters [S]',

    --[96]  = 'Unknown Survival Guide',
    --[97]  = 'Unknown Survival Guide',
    --[98]  = 'Unknown Survival Guide',
    --[99]  = 'Unknown Survival Guide',
    --[100]  = 'Unknown Survival Guide',
    --[101]  = 'Unknown Survival Guide',
    [102] = 'Eastern Adoulin',
    [103] = 'Zeruhn Mines',
}