return {
	[0] = "West Ronfaure",
	[1] = "Valkurm Dunes",
	[2] = "Jugner Forest",
	[3] = "North Gustaberg",
	[4] = "Pashhow Marshlands",
	[5] = "West Sarutabaruta",
	[6] = "Buburimu Peninsula",
	[7] = "Beaucedine Glacier",
	
	[8] = "Xarcabard",
	[9] = "Qufim Island",
	[10] = "Meriphataud Mountains",
	[11] = "The Sanctuary of Zi'Tah",
	[12] = "Eastern Altepa Desert",
	[13] = "Cape Teriggan",
	[14] = "Yuhtunga Jungle",
	[15] = "Yhoator Jungle",
	
	[16] = "Lufaise Meadows",
	[17] = "Ru'Aun Gardens",
	[18] = "Oldton Movalpolos",
	[19] = "Bostaunieux Oubliette",
	[20] = "Toraimarai Canal",
	[21] = "The Eldieme Necropolis",
	[22] = "Crawlers' Nest",
	[23] = "Garlaige Citadel",
	
	[24] = "Northern San d'Oria",
	[25] = "Bastok Mines",
	[26] = "Port Windurst",
	[27] = "Ru'Lude Gardens",
	[28] = "La Theine Plateau",
	[29] = "Batallia Downs",
	[30] = "Konschtat Highlands",
	[31] = "Rolanberry Fields",
	
	[32] = "Tahrongi Canyon",
	[33] = "Sauromugue Champaign",
	[34] = "Fort Ghelsba",
	[35] = "Beadeaux",
	[36] = "Davoi",
	[37] = "Castle Oztroja",
	[38] = "Castle Zvahl Baileys",
	[39] = "Ranguemont Pass",
	
	[40] = "Lower Delkfutt's Tower",
	[41] = "King Ranperre's Tomb",
	[42] = "Dangruf Wadi",
	[43] = "Inner Horutoto Ruins",
	[44] = "Ordelle's Caves",
	[45] = "Gusgen Mines",
	[46] = "Maze of Shakhrami",
	[47] = "Ro'Maeve",
	
	[48] = "Western Altepa Desert",
	[49] = "Temple of Uggalepih",
	[50] = "Korroloka Tunnel",
	[51] = "Kuftal Tunnel",
	[52] = "Sea Serpent Grotto",
	[53] = "Gustav Tunnel",
	[54] = "Labyrinth of Onzozo",
	[55] = "Carpenters' Landing",
	
	[56] = "Bibiki Bay",
	[57] = "Misareaux Coast",
	[58] = "Phomiuna Aqueducts",
	[59] = "Sacrarium",
	[60] = "Wajaom Woodlands",
	[61] = "Mamook",
	[62] = "Aydeewa Subterrane",
	[63] = "East Ronfaure [S]",
	
	[64] = "Jugner Forest [S]",
	[65] = "Vunkerl Inlet [S]",
	[66] = "Batallia Downs [S]",
	[67] = "North Gustaberg [S]",
	[68] = "Grauberg [S]",
	[69] = "Pashhow Marshlands [S]",
	[70] = "Rolanberry Fields [S]",
	[71] = "West Sarutabaruta [S]",
	
	[72] = "Fort Karugo-Narugo [S]",
	[73] = "Meriphataud Mountains [S]",
	[74] = "Sauromugue Champaign [S]",
	[75] = "Beaucedine Glacier [S]",
	[76] = "Castle Zvahl Baileys [S]",
	[77] = "Garlaige Citadel [S]",
	[78] = "Crawlers' Nest [S]",
	[79] = "The Eldieme Necropolis [S]",
	
	[80] = "Kazham",
	[81] = "Norg",
	[82] = "Rabao",
	[83] = "Tavnazian Safehold",
	[84] = "Aht Urhgan Whitegate",
	[85] = "Nashmau",
	[86] = "Southern San d'Oria [S]",
	--[87] = "Unknown Survival Guide",
	
	[88] = "Windurst Waters [S]",
	[89] = "Caedarva Mire",
	[90] = "Arrapago Reef",
	[91] = "Halvung",
	[92] = "Behemoth's Dominion",
	[93] = "Dragon's Aery",
	[94] = "Valley of Sorrows",
	[95] = "Ifrit's Cauldron",
	
	--[96] = "Unknown Survival Guide",
	--[97] = "Unknown Survival Guide",
	--[98] = "Unknown Survival Guide",
	--[99] = "Unknown Survival Guide",
	--[100] = "Unknown Survival Guide",
	--[101] = "Unknown Survival Guide",
	[102] = "Zeruhn Mines",
	[103] = "Eastern Adoulin",

	--[104] = "Unknown Survival Guide",
	--[105] = "Unknown Survival Guide",
	--[106] = "Unknown Survival Guide",
	--[107] = "Unknown Survival Guide",
	--[108] = "Unknown Survival Guide",
	--[109] = "Unknown Survival Guide",
	--[110] = "Unknown Survival Guide",
	--[111] = "Unknown Survival Guide",
	
	--[112] = "Unknown Survival Guide",
	--[113] = "Unknown Survival Guide",
	--[114] = "Unknown Survival Guide",
	--[115] = "Unknown Survival Guide",
	--[116] = "Unknown Survival Guide",
	--[117] = "Unknown Survival Guide",
	--[118] = "Unknown Survival Guide",
	--[119] = "Unknown Survival Guide",
	
	--[120] = "Unknown Survival Guide",
	--[121] = "Unknown Survival Guide",
	--[122] = "Unknown Survival Guide",
	--[123] = "Unknown Survival Guide",
	--[124] = "Unknown Survival Guide",
	--[125] = "Unknown Survival Guide",
	--[126] = "Unknown Survival Guide",
	--[127] = "Unknown Survival Guide",
}